// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace TreasurersApp.Database
{
    using Newtonsoft.Json;

    // EmailType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class EmailType
    {
        public int EmailTypeId { get; set; } // EmailTypeID (Primary key)
        public string Name { get; set; } // Name (length: 10)
        public string Description { get; set; } // Description (length: 50)
        public bool Active { get; set; } // Active
        public System.Guid CreatedBy { get; set; } // CreatedBy
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public System.Guid LastModifiedBy { get; set; } // LastModifiedBy
        public System.DateTime LastModifiedDate { get; set; } // LastModifiedDate
    }

}
// </auto-generated>
